# Generated by Django 5.2 on 2025-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewvideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='converted_video',
            field=models.FileField(blank=True, null=True, upload_to='converted/'),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='face_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
    ]
