# Generated by Django 5.2.1 on 2025-05-18 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_interviewvideo_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
