# Generated by Django 5.2.1 on 2025-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewvideo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewvideo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
