# Generated by Django 5.2.1 on 2025-05-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_interviewvideo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewvideo',
            name='dominant_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewvideo',
            name='emotion_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
